### ISSUE TITLE
PHP 大文件行号

### ISSUE THREAD

**Issue by youmikuang** [ZvanYang/PHP-interview-myway#1]
```php

<?php

// index.php 的大小为 1.7 G 行数为 1 亿+  用时 6s-
$getfp = fopen('./index.php', 'r');

$lines = 0;

while (fgets($getfp)) {
    $lines++;
}
fclose($getfp); //关闭文件

var_dump($lines)
```

**Comment by disxo** [comment]
啊？不会同步处理这么多，不会占用内存太多么？

**Comment by Chasers9527** [comment]
@disxo  内存占用倒是没看。。。。我 32G 台式机。。

**Comment by danJian** [comment]
内存占用是不会的。fopen打开文件，返回文件资源，这一步并不会将文件直接加载到内存中。fgets操作是获取当前行（通过换行符界定）内容，然后将文件指针移动至今下一行开头，换句话说fgets单次只操作只操作单行的内容。但是如果一个文件有100G只有1行，估计照样会内存溢出。fgets最好的方式是指定一下内容大小fgets($fp,10);只取当前行前10个字符。

**Comment by danJian** [comment]
PHP 标准库中提供了SplFileInfo和SplFileObject标准操作类，通过SplFileObject->seek()方法可以将文件指针移动至指定行，如果行数不存在会返回false。那么可以通过二分查找进一步提升效率：大致如下：
首先通过以下方式确定边界值
n = 1
seek(n*=2)
如果返回false表示最大行号在n当前值和 n/2之间，然后二分。
底层文件操作可能需要移动的文件指针量一致。但是计算量会少很多。

**Comment by i365star** [comment]
我又查了下文档，fgets其实是有单行最大长度限制的，默认1024，所以不会内存溢出，但是依然存在单行过长，导致的数据不准确。所以更严谨一点的做法应该是取得行的内容后检查换行符
