### ISSUE TITLE
关于 redis 缓存不一致的看法

### ISSUE THREAD

**Issue by linchupeng** [ZvanYang/PHP-interview-myway#2]
文章说到 ：先删除缓存，再更新数据库 但是这个细节如果在两个并发操作的时候就会有脏数据 
一个是更新操作，另一个是查询操作，更新操作删除缓存后，查询操作没有命中缓存，先把老数据读出来后放到缓存中，然后更新操作更新了数据库。于是，在缓存中的数据还是老的数据，导致缓存中的数据是脏的，而且还一直这样脏下去了。

可以参考系这篇 [更新缓存讨论](https://coolshell.cn/articles/17416.html)

**Comment by disxo** [comment]
是的是的， 看过这篇哈，我有空再整理一下哈

**Comment by feng99** [comment]
肯定是要先更新数据库,再删除 或者 更新缓存的.

**Comment by feng99** [comment]
如果是string结构 就是删除 缓存  如果是hash结构  就是更新缓存(更新部分字段)

**Comment by linchupeng** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
