### ISSUE TITLE
MySQL大表建索引

### ISSUE THREAD

**Issue by i365star** [ZvanYang/PHP-interview-myway#4]
文中提到的方案不大对吧。如果先建临时表，然后rename，给原表加索引，再进行数据修复，依然会影响线上服务，而且原表加索引的时间依然很长，会出现主从延迟。
一般业务上，都是通过创建新表，然后将旧表数据同步至新表，再rename进行的。DBA有相关的MySQL工具，但是在该表存在单行短时间频繁写入的情况下，依然会有因为无法取得锁而导致的死锁现象发生。所以切换的行为还是手动在低峰时间操作更安全一些。

**Comment by disxo** [comment]
感觉你的操作方式，算是渐进式hash

这个方案是按《MySQL45讲》里面的一个思路来弄的吧，我记得

**Comment by i365star** [comment]
其实是重建新表和替换，这样可以降低瞬间IO。只是rename依然需要取得写锁。如果不能长时间都不能取得写锁，就会出现死锁现象
