### ISSUE TITLE
php秒杀系统

### ISSUE THREAD

**Issue by i365star** [ZvanYang/PHP-interview-myway#5]
这个秒杀系统不严谨吧，如果两个并发请求，同时取得get(goods.num)，全等于1，然后再同时减-1，这个系统拦不住哇，你还是需要检查decr的返回值的

**Comment by disxo** [comment]
嗯，还有一个锁，加锁的时候可以判断一下呢？
锁有唯一性

**Comment by i365star** [comment]
哦，我看错了，是value，看成key了。但是这样不好吧，在秒杀的高并发的场景下，你改成了串行执行？
